// lib/mockData.ts — Toutes les données du site en mode mock

export const MOCK_PRODUCTS = [
  { id: '1', name: "Lait hydratant démêlant (leave-in)", description: "Soin quotidien sans rinçage à base de lait d'avoine, vanille, huile d'abyssinie et d'avocat. Parfait pour les cheveux secs et afros.", price: 18.00, category: "Soins capillaires", stock: 50, imageUrl: "https://danynaturalconcept.org/wp-content/uploads/2015/12/lait-capillaire-demelant-hydratant-510x510.png" },
  { id: '2', name: "Sérum prodigieux croissance", description: "Favorise la pousse et fortifie la fibre capillaire grâce à ses actifs naturels concentrés.", price: 25.00, category: "Soins capillaires", stock: 30, imageUrl: "https://danynaturalconcept.org/wp-content/uploads/2020/02/serum-prodigieux-DNC-510x510.jpg" },
  { id: '3', name: "Poudre de chébé authentique du Tchad", description: "Le secret de beauté millénaire des femmes tchadiennes pour des cheveux longs, forts et brillants.", price: 15.00, category: "Soins capillaires", stock: 100, imageUrl: "https://danynaturalconcept.org/wp-content/uploads/2019/01/FotoGrid_20240515_094328468-510x507.jpg" },
  { id: '4', name: "Baume tropical fondant (mangue & aloe vera)", description: "Nutrition intense pour cheveux secs et déshydratés. Referme les écailles et apporte brillance.", price: 15.00, category: "Soins capillaires", stock: 40, imageUrl: "https://danynaturalconcept.org/wp-content/uploads/2015/12/Baume-tropical-fondant-mangue-510x510.png" },
  { id: '5', name: "Pack soin capillaire complet", description: "La routine complète : Shampoing doux + Soin profond + Baume tropical + Lait démêlant + Sérum croissance.", price: 82.00, category: "Soins capillaires", stock: 15, imageUrl: "https://danynaturalconcept.org/wp-content/uploads/2016/03/PhotoGrid_1565190847319-1-510x510.jpg" },
  { id: '6', name: "Soin profond démêlant et revitalisant", description: "Masque intensif pour nourrir en profondeur, réparer et redonner vie aux cheveux abîmés.", price: 20.00, category: "Soins capillaires", stock: 25, imageUrl: "https://danynaturalconcept.org/wp-content/uploads/2015/12/PhotoGrid_1565269967310-510x510.jpg" },
  { id: '7', name: "Shampoing adoucissant miel & ortie", description: "Nettoyage en douceur pour cuir chevelu sensible. Formule douce et naturelle.", price: 14.00, category: "Soins capillaires", stock: 60, imageUrl: "https://danynaturalconcept.org/wp-content/uploads/2016/02/Shampoing-adoucissant-miel-ortie-DNC-1-510x510.jpg" },
  { id: '8', name: "Savon noir purifiant DNC", description: "Savon traditionnel 100% naturel pour une peau nette et purifiée, visage et corps.", price: 7.00, category: "Soins du corps", stock: 80, imageUrl: "https://danynaturalconcept.org/wp-content/uploads/2019/08/PhotoGrid_1564986935974-1-510x510.jpg" },
  { id: '9', name: "Baume fondant cacao & aloe vera", description: "Soin corporel riche et protecteur au beurre de cacao et gel d'aloe vera. 250ml.", price: 22.00, category: "Soins du corps", stock: 35, imageUrl: "https://danynaturalconcept.org/wp-content/uploads/2019/01/PhotoGrid_1565185949774-510x510.jpg" },
  { id: '10', name: "Lait de jour matifiant visage", description: "Équilibre le sébum et hydrate sans graisser. Idéal pour peaux mixtes à grasses.", price: 20.00, category: "Soins du visage", stock: 20, imageUrl: "https://danynaturalconcept.org/wp-content/uploads/2017/10/PhotoGrid_1565186545390-510x510.jpg" },
  { id: '11', name: "Beurre de karité bio brut", description: "100% pur, non raffiné, originaire du Burkina Faso. Protection et nutrition intense. 100g.", price: 10.00, category: "Beurres végétaux", stock: 120, imageUrl: "https://danynaturalconcept.org/wp-content/uploads/2018/06/beurre-de-karite-510x510.jpg" },
  { id: '12', name: "Guide de recettes cosmétiques de Dany", description: "Livre numérique complet pour apprendre à fabriquer ses propres soins naturels maison.", price: 12.00, category: "Livres & Guides", stock: 500, imageUrl: "https://danynaturalconcept.org/wp-content/uploads/2017/12/IMG_20171204_134706_347-510x510.jpg" },
  { id: '13', name: "Huile de palmiste bio", description: "Fortifiant capillaire traditionnel d'Afrique de l'Ouest. Nutrition et brillance.", price: 10.00, category: "Huiles végétales", stock: 45, imageUrl: "https://danynaturalconcept.org/wp-content/uploads/2016/03/PhotoGrid_1581423068335-510x510.jpg" },
  { id: '14', name: "Huile anti-imperfections & cicatrisante", description: "Soin ciblé pour les problèmes de peau : taches, acné, cicatrices.", price: 25.00, category: "Soins du visage", stock: 25, imageUrl: "https://danynaturalconcept.org/wp-content/uploads/2018/12/PhotoGrid_1565185116754-510x510.jpg" },
  { id: '15', name: "Beurre de cacao bio en pastilles", description: "Soin corporel gourmand et protecteur au parfum vanillé naturel.", price: 10.00, category: "Beurres végétaux", stock: 55, imageUrl: "https://danynaturalconcept.org/wp-content/uploads/2016/03/CocoaButterWafers_OIL81_Main-510x510.jpg" },
  { id: '16', name: "Velouté hydratant corps", description: "Texture légère et fondante pour une hydratation douce et quotidienne.", price: 19.00, category: "Soins du corps", stock: 30, imageUrl: "https://danynaturalconcept.org/wp-content/uploads/2018/06/PhotoGrid_1564835428611-510x510.jpg" },
  { id: '17', name: "Élixir de massage relaxant", description: "Synergie d'huiles essentielles et végétales pour une détente profonde.", price: 18.00, category: "Soins du corps", stock: 20, imageUrl: "https://danynaturalconcept.org/wp-content/uploads/2019/07/PhotoGrid_1564989791373-510x510.jpg" },
  { id: '18', name: "Beurre de mangue artisanal", description: "Riche en antioxydants, idéal pour protéger et nourrir cheveux et peau.", price: 15.00, category: "Beurres végétaux", stock: 40, imageUrl: "https://danynaturalconcept.org/wp-content/uploads/2024/11/FotoGrid_20241122_134441149-510x533.jpg" },
  { id: '19', name: "Synergie huiles raffermissantes", description: "Aide à tonifier et raffermir la peau. Idéal pour l'après grossesse.", price: 28.00, category: "Soins du corps", stock: 15, imageUrl: "https://danynaturalconcept.org/wp-content/uploads/2018/06/PhotoGrid_1564990158865-510x510.jpg" },
  { id: '20', name: "Pack routine éclat visage", description: "Savon noir + Lait matifiant + Huile anti-imperfections. La routine complète.", price: 45.00, category: "Soins du visage", stock: 10, imageUrl: "https://danynaturalconcept.org/wp-content/uploads/2017/10/pack-visage-dnc-510x510.jpg" },
  { id: '21', name: "Huile de baobab bio", description: "Nutrition intense pour peaux sèches et très sèches. Riche en vitamines.", price: 12.00, category: "Huiles végétales", stock: 30, imageUrl: "https://danynaturalconcept.org/wp-content/uploads/2016/03/huile-baobab-510x510.jpg" },
  { id: '22', name: "Beurre de sal bio", description: "Alternative raffinée au karité, texture encore plus fine et soyeuse.", price: 14.00, category: "Beurres végétaux", stock: 20, imageUrl: "https://danynaturalconcept.org/wp-content/uploads/2023/05/beurre-de-sal-510x510.jpg" }
];

export const MOCK_SERVICES = [
  { id: 's1', title: "Consultation Naturopathie (1h)", description: "Bilan complet de santé naturelle : nutrition, gestion du stress, hygiène de vie.", duration: 60, price: 50.00, icon: "🌿", color: "from-green-50 to-emerald-50" },
  { id: 's2', title: "Soin ou Relaxation (1h)", description: "Réflexologie plantaire, massage thérapeutique ou séance de relaxation profonde.", duration: 60, price: 50.00, icon: "✨", color: "from-purple-50 to-violet-50" },
  { id: 's3', title: "Suivi Naturopathique (3 séances)", description: "Accompagnement complet sur le long terme pour des résultats profonds et durables.", duration: 180, price: 120.00, icon: "📈", color: "from-blue-50 to-sky-50" },
  { id: 's4', title: "Diagnostic Capillaire + Routine", description: "Analyse approfondie de votre cuir chevelu et création d'une routine personnalisée.", duration: 45, price: 60.00, icon: "💆", color: "from-amber-50 to-yellow-50" },
  { id: 's5', title: "Diagnostic Peau + Routine", description: "Diagnostic complet de votre peau et conseils en cosmétique naturelle sur-mesure.", duration: 45, price: 85.00, icon: "🌸", color: "from-rose-50 to-pink-50" }
];

export const CATEGORIES = ['Tous', 'Soins capillaires', 'Soins du corps', 'Soins du visage', 'Beurres végétaux', 'Huiles végétales', 'Livres & Guides'];

export const TIME_SLOTS = [
  '09:00', '09:30', '10:00', '10:30', '11:00', '11:30',
  '14:00', '14:30', '15:00', '15:30', '16:00', '16:30', '17:00', '17:30', '18:00', '18:30'
];
